language: go
go:
  - 1.7
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
script:
  - go test ./...
after_success:
  - "[[ $TRAVIS_BRANCH =~ (^v[0-9]+.[0-9]+.[0-9]+) ]] && gox -output dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - "[[ $TRAVIS_BRANCH =~ (^v[0-9]+.[0-9]+.[0-9]+) ]] && ghr --username tcnksm-sample --token $GITHUB_TOKEN --replace dist/"
